xcopy /s/y/i/f/d "..\dali-adaptor\dali\integration-api\*.h" "..\dali-env\opt\include\dali\integration-api\adaptors"
xcopy /s/y/i/f/d "..\dali-env\opt\include\dali\integration-api\adaptors\windows\*.*" "..\dali-env\opt\include\dali\integration-api\adaptors"
copy /d "..\dali-adaptor\dali\public-api\dali.h" "..\dali-env\opt\include\dali\dali.h"

xcopy /s/y/i/f/d "..\dali-toolkit\dali-toolkit\styles\*.json" "..\dali-env\opt\share\dali\toolkit\styles"
xcopy /s/y/i/f/d "..\dali-toolkit\dali-toolkit\styles\480x800\*.json" "..\dali-env\opt\share\dali\toolkit\styles"
xcopy /s/y/i/f/d "..\dali-toolkit\dali-toolkit\styles\480x800\images\*.png" "..\dali-env\opt\share\dali\toolkit\styles\images"
xcopy /s/y/i/f/d "..\dali-toolkit\dali-toolkit\styles\images-common\*.png" "..\dali-env\opt\share\dali\toolkit\images"
xcopy /s/y/i/f/d "..\dali-toolkit\dali-toolkit\sounds\*.ogg" "..\dali-env\opt\share\dali\toolkit\sounds"

xcopy /s/y/i/f/d "..\dali-demo\resources\game\*.*" "..\dali-env\opt\share\com.samsung.dali-demo\res\game"
xcopy /s/y/i/f/d "..\dali-demo\resources\images\*.*" "..\dali-env\opt\share\com.samsung.dali-demo\res\images"
xcopy /s/y/i/f/d "..\dali-demo\resources\models\*.*" "..\dali-env\opt\share\com.samsung.dali-demo\res\models"
xcopy /s/y/i/f/d "..\dali-demo\resources\scripts\*.json" "..\dali-env\opt\share\com.samsung.dali-demo\res\scripts"
xcopy /s/y/i/f/d "..\dali-demo\resources\shaders\*.*" "..\dali-env\opt\share\com.samsung.dali-demo\res\shaders"
xcopy /s/y/i/f/d "..\dali-demo\resources\style\*.json" "..\dali-env\opt\share\com.samsung.dali-demo\res\style"
xcopy /s/y/i/f/d "..\dali-demo\resources\style\images\*.png" "..\dali-env\opt\share\com.samsung.dali-demo\res\style\images"
xcopy /s/y/i/f/d "..\dali-demo\resources\videos\*.*" "..\dali-env\opt\share\com.samsung.dali-demo\res\videos"
xcopy /s/y/i/f/d "ExDll\*.dll" "..\bin\Debug"
xcopy /s/y/i/f/d "ExDll\*.dll" "..\bin\Release"
@pause